version: "3"
volumes:
  nextjs-node-modules:
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "npm i && npm run dev"
    volumes:
      - .:/app
      - nextjs-node-modules:/app/node_modules
    ports:
      - 3000:3000
      - 6006:6006
    depends_on:
      - db
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
