version: "3"
volumes:
  nextjs-node-modules:
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "npm run dev"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
      - nextjs-node-modules:/app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DISPLAY=:0
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
