version: "3"
services:
  web:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=database_url_goes_here
