FROM mcr.microsoft.com/playwright

ENV PWUSER pwuser

COPY package*.json ./

RUN apt-get update && \
    apt-get install -y sudo curl git openjdk-11-jdk && \ 
    usermod -aG sudo $PWUSER && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' | tee -a /etc/sudoers && \
    npm i --force && \
    npx playwright install-deps

RUN curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

WORKDIR /home/$PWUSER/app

RUN sudo chown -R $PWUSER:$PWUSER /home/$PWUSER/app

COPY --chown=$PWUSER:$PWUSER . .

RUN npx prisma generate
RUN cd audiveris && \
    git config --global --add safe.directory /home/pwuser/app/audiveris && \
    ./gradlew build && \
    tar -xf build/distributions/Audiveris-5.2.5.tar

EXPOSE 3000
CMD ["npm", "run", "dev"]