FROM mcr.microsoft.com/playwright:v1.16.3-focal

ENV PWUSER pwuser

COPY package*.json ./

RUN apt-get update && \
    apt-get install -y sudo git openjdk-11-jdk tesseract-ocr-rus && \
    usermod -aG sudo $PWUSER && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' | tee -a /etc/sudoers && \
    npm i -g npm && \
    npx playwright install-deps

WORKDIR /home/$PWUSER/app
RUN git clone https://github.com/Audiveris/audiveris.git && \
    cd audiveris && \
    ./gradlew build && \
    tar -xf build/distributions/Audiveris-5.2.5.tar

RUN sudo chown -R $PWUSER:$PWUSER /home/$PWUSER/app
COPY --chown=$PWUSER:$PWUSER . .

EXPOSE 3000

CMD ["npm", "run", "dev"]