version: "3"
services:
  db:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    env_file:
      - .env.production

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    ports:
      - "3000:3000"
    image: node:16-alpine

  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOMAINS: tunescore.dev -> http://web:3000
      STAGE: production
