version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "npm run dev & npm run storybook"
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 6006:6006
    depends_on:
      - db
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
