version: "3"
volumes:
  nextjs-node-modules:
services:
  db:
    image: "bitnami/mongodb:latest"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"

  web:
    build: .
    command: bash -c "npm ci --legacy-peer-deps && npm run dev"
    volumes:
      - .:/app
      - nextjs-node-modules:/app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DISPLAY=:0
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
