FROM mcr.microsoft.com/playwright

ENV PWUSER pwuser

COPY package*.json ./

RUN apt-get update && \
    apt-get install -y sudo curl git openjdk-11-jdk && \ 
    usermod -aG sudo $PWUSER && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' | tee -a /etc/sudoers && \
    npm ci --force && \
    npx playwright install-deps

RUN curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

WORKDIR /home/$PWUSER/app

RUN sudo chown -R $PWUSER:$PWUSER /home/$PWUSER/app

COPY --chown=$PWUSER:$PWUSER . . 

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "dev"]