# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "Albums", type: :request, openapi: false do
  # This should return the minimal set of attributes required to create a valid
  # Album. As you add validations to Album, be sure to
  # adjust the attributes here as well.
  let!(:album) { attributes_for :album }

  let!(:album_title_empty) { attributes_for :album, :title_empty }

  describe 'GET /index' do
    context 'should success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /show' do
    context 'should be success' do
      let(:id) { create(:album).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /new' do
    context 'should be success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /edit' do
    context 'should be success' do
      let(:id) { create(:album).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'POST /create' do
    context 'should be success' do
      let(:params) { { album: album_title_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity
    end

    context 'with valid parameters' do
      it 'creates a new Album' do
        expect do
          post albums_url, params: { album: }
        end.to change(Album, :count).by(1)
      end

      it 'redirects to the created album' do
        post albums_url, params: { album: }
        expect(response).to redirect_to(album_url(Album.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Album' do
        expect do
          post albums_url, params: { album: album_title_empty }
        end.to change(Album, :count).by(0)
      end
    end
  end

  describe 'POST /create json' do
    context 'should be success' do
      let(:params) { { album: } }

      it_behaves_like 'respond_with', :created, openapi: true
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_album) { attributes_for :album }

      it 'updates the requested album' do
        album = create(:album)
        patch album_url(album), params: { album: new_album }
        album.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the album' do
        album = create(:album)
        patch album_url(album), params: { album: new_album }
        album.reload
        expect(response).to redirect_to(album_url(album))
      end
    end

    context 'should be success' do
      let(:id) { create(:album).id }
      let(:params) { { album: album_title_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested album' do
      album = create(:album)
      expect do
        delete album_url(album)
      end.to change(Album, :count).by(-1)
    end

    it 'redirects to the albums list' do
      album = create(:album)
      delete album_url(album)
      expect(response).to redirect_to(albums_url)
    end
  end
end
