# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "Artists", type: :request, openapi: false do
  # This should return the minimal set of attributes required to create a valid
  # Artist. As you add validations to Artist, be sure to
  # adjust the attributes here as well.
  let(:artist) do
    attributes_for :artist
  end

  let(:artist_name_empty) do
    attributes_for :artist, :name_empty
  end

  describe 'GET /index' do
    context 'should success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /show' do
    context 'should be success' do
      let(:id) { create(:artist).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /new' do
    context 'should be success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /edit' do
    context 'should be success' do
      let(:id) { create(:artist).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'POST /create' do
    context 'should be success' do
      let(:params) { { artist: artist_name_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity
    end

    context 'with valid parameters' do
      it 'creates a new Artist' do
        expect do
          post artists_url, params: { artist: }
        end.to change(Artist, :count).by(1)
      end

      it 'redirects to the created artist' do
        post artists_url, params: { artist: }
        expect(response).to redirect_to(artist_url(Artist.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Artist' do
        expect do
          post artists_url, params: { artist: artist_name_empty }
        end.to change(Artist, :count).by(0)
      end
    end
  end

  describe 'POST /create json', openapi: true do
    context 'should be success' do
      let(:params) { { artist: artist_name_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity, openapi: true
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_artist) { attributes_for :artist }

      it 'updates the requested artist' do
        artist = create(:artist)
        patch artist_url(artist), params: { artist: new_artist }
        artist.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the artist' do
        artist = create(:artist)
        patch artist_url(artist), params: { artist: new_artist }
        artist.reload
        expect(response).to redirect_to(artist_url(artist))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested artist' do
      artist = create :artist
      expect do
        delete artist_url(artist)
      end.to change(Artist, :count).by(-1)
    end

    it 'redirects to the artists list' do
      artist = create :artist
      delete artist_url(artist)
      expect(response).to redirect_to(artists_url)
    end
  end
end
