# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "Bands", type: :request, openapi: false do
  # This should return the minimal set of attributes required to create a valid
  # Band. As you add validations to Band, be sure to
  # adjust the attributes here as well.
  let(:band) do
    attributes_for :band
  end

  let(:band_name_empty) do
    attributes_for :band, :name_empty
  end

  describe 'GET /index' do
    context 'should success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /show' do
    context 'should be success' do
      let(:id) { create(:band).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /new' do
    context 'should be success' do
      it_behaves_like 'respond_with', :success
    end
  end

  describe 'GET /edit' do
    context 'should be success' do
      let(:id) { create(:band).id }

      it_behaves_like 'respond_with', :success
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Band' do
        expect do
          post bands_url, params: { band: }
        end.to change(Band, :count).by(1)
      end

      it 'redirects to the created band' do
        post bands_url, params: { band: }
        expect(response).to redirect_to(band_url(Band.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Band' do
        expect do
          post bands_url, params: { band: band_name_empty }
        end.to change(Band, :count).by(0)
      end
    end

    context 'should be success' do
      let(:id) { create(:bands).id }
      let(:params) { { band: band_name_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity
    end
  end

  describe 'POST /create json', openapi: true do
    context 'should be success' do
      let(:params) { { band: band_name_empty } }

      it_behaves_like 'respond_with', :unprocessable_entity, openapi: true
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) { attributes_for :band }

      # TODO:
      # it "updates the requested band" do
      #   band = Band.create! valid_attributes
      #   patch band_url(band), params: { band: new_attributes }
      #   band.reload
      #   expect(response).to have_http_status(:unprocessable_entity)
      # end

      it 'redirects to the band' do
        band = create(:band)
        patch band_url(band), params: { band: new_attributes }
        band.reload
        expect(response).to redirect_to(band_url(band))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        band = create(:band)
        patch band_url(band), params: { band: band_name_empty }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested band' do
      band = create(:band)
      expect do
        delete band_url(band)
      end.to change(Band, :count).by(-1)
    end

    it 'redirects to the bands list' do
      band = create(:band)
      delete band_url(band)
      expect(response).to redirect_to(bands_url)
    end
  end
end
