require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/musics", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Music. As you add validations to Music, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for :music }

  let(:invalid_attributes) { attributes_for :music_title_empty }

  describe "GET /index" do
    it "renders a successful response" do
      Music.create! valid_attributes
      get musics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      music = Music.create! valid_attributes
      get music_url(music)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_music_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      music = Music.create! valid_attributes
      get edit_music_url(music)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Music" do
        expect {
          post musics_url, params: { music: valid_attributes }
        }.to change(Music, :count).by(1)
      end

      it "redirects to the created music" do
        post musics_url, params: { music: valid_attributes }
        expect(response).to redirect_to(music_url(Music.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Music" do
        expect {
          post musics_url, params: { music: invalid_attributes }
        }.to change(Music, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post musics_url, params: { music: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { attributes_for :music }

      # it "updates the requested music" do
      #   music = Music.create! valid_attributes
      #   patch music_url(music), params: { music: new_attributes }
      #   music.reload
      #   expect(response).to be_successful
      # end

      it "redirects to the music" do
        music = Music.create! valid_attributes
        patch music_url(music), params: { music: new_attributes }
        music.reload
        expect(response).to redirect_to(music_url(music))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        music = Music.create! valid_attributes
        patch music_url(music), params: { music: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested music" do
      music = Music.create! valid_attributes
      expect {
        delete music_url(music)
      }.to change(Music, :count).by(-1)
    end

    it "redirects to the musics list" do
      music = Music.create! valid_attributes
      delete music_url(music)
      expect(response).to redirect_to(musics_url)
    end
  end
end
