name: Build Next.js

on:
  push:
    branches:
      - "main"

jobs:
  next-js-build:
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16.x

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Create Build Folder
        run: mkdir build

      - name: Move
        run: mv .next prisma package.json package-lock.json Dockerfile docker-compose.yml docker-compose.prod.yml build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
